package war.metaphor.mutator.virtualization;

import java.security.SecureRandom;

public final class VmOpcodes {

    private static final SecureRandom RNG = new SecureRandom();

    public static final int NOP;
    public static final int IPUSH;
    public static final int LPUSH;
    public static final int FPUSH;
    public static final int DPUSH;
    public static final int APUSH;
    public static final int ACONST_NULL;
    public static final int ILOAD;
    public static final int LLOAD;
    public static final int FLOAD;
    public static final int DLOAD;
    public static final int ALOAD;
    public static final int ISTORE;
    public static final int LSTORE;
    public static final int FSTORE;
    public static final int DSTORE;
    public static final int ASTORE;
    public static final int POP;
    public static final int POP2;
    public static final int DUP;
    public static final int DUP_X1;
    public static final int DUP_X2;
    public static final int DUP2;
    public static final int DUP2_X1;
    public static final int DUP2_X2;
    public static final int SWAP;
    public static final int IADD;
    public static final int LADD;
    public static final int FADD;
    public static final int DADD;
    public static final int ISUB;
    public static final int LSUB;
    public static final int FSUB;
    public static final int DSUB;
    public static final int IMUL;
    public static final int LMUL;
    public static final int FMUL;
    public static final int DMUL;
    public static final int IDIV;
    public static final int LDIV;
    public static final int FDIV;
    public static final int DDIV;
    public static final int IREM;
    public static final int LREM;
    public static final int FREM;
    public static final int DREM;
    public static final int INEG;
    public static final int LNEG;
    public static final int FNEG;
    public static final int DNEG;
    public static final int ISHL;
    public static final int LSHL;
    public static final int ISHR;
    public static final int LSHR;
    public static final int IUSHR;
    public static final int LUSHR;
    public static final int IAND;
    public static final int LAND;
    public static final int IOR;
    public static final int LOR;
    public static final int IXOR;
    public static final int LXOR;
    public static final int I2L;
    public static final int I2F;
    public static final int I2D;
    public static final int L2I;
    public static final int L2F;
    public static final int L2D;
    public static final int F2I;
    public static final int F2L;
    public static final int F2D;
    public static final int D2I;
    public static final int D2L;
    public static final int D2F;
    public static final int I2B;
    public static final int I2C;
    public static final int I2S;
    public static final int LCMP;
    public static final int FCMPL;
    public static final int FCMPG;
    public static final int DCMPL;
    public static final int DCMPG;
    public static final int IFEQ;
    public static final int IFNE;
    public static final int IFLT;
    public static final int IFGE;
    public static final int IFGT;
    public static final int IFLE;
    public static final int IF_ICMPEQ;
    public static final int IF_ICMPNE;
    public static final int IF_ICMPLT;
    public static final int IF_ICMPGE;
    public static final int IF_ICMPGT;
    public static final int IF_ICMPLE;
    public static final int IF_ACMPEQ;
    public static final int IF_ACMPNE;
    public static final int GOTO;
    public static final int IRETURN;
    public static final int LRETURN;
    public static final int FRETURN;
    public static final int DRETURN;
    public static final int ARETURN;
    public static final int RETURN;
    public static final int GETSTATIC;
    public static final int PUTSTATIC;
    public static final int GETFIELD;
    public static final int PUTFIELD;
    public static final int INVOKEVIRTUAL;
    public static final int INVOKESPECIAL;
    public static final int INVOKESTATIC;
    public static final int INVOKEINTERFACE;
    public static final int NEW;
    public static final int NEWARRAY;
    public static final int ANEWARRAY;
    public static final int ARRAYLENGTH;
    public static final int ATHROW;
    public static final int CHECKCAST;
    public static final int INSTANCEOF;
    public static final int IFNULL;
    public static final int IFNONNULL;
    public static final int TABLESWITCH;
    public static final int LOOKUPSWITCH;
    public static final int MULTIANEWARRAY;
    public static final int IALOAD;
    public static final int LALOAD;
    public static final int FALOAD;
    public static final int DALOAD;
    public static final int AALOAD;
    public static final int BALOAD;
    public static final int CALOAD;
    public static final int SALOAD;
    public static final int IASTORE;
    public static final int LASTORE;
    public static final int FASTORE;
    public static final int DASTORE;
    public static final int AASTORE;
    public static final int BASTORE;
    public static final int CASTORE;
    public static final int SASTORE;
    public static final int IINC;
    public static final int MONITORENTER;
    public static final int MONITOREXIT;

    static {
        int[] pool = RNG.ints(0, Integer.MAX_VALUE).distinct().limit(142).toArray();
        int i = 0;
        NOP            = pool[i++];
        IPUSH          = pool[i++];
        LPUSH          = pool[i++];
        FPUSH          = pool[i++];
        DPUSH          = pool[i++];
        APUSH          = pool[i++];
        ACONST_NULL    = pool[i++];
        ILOAD          = pool[i++];
        LLOAD          = pool[i++];
        FLOAD          = pool[i++];
        DLOAD          = pool[i++];
        ALOAD          = pool[i++];
        ISTORE         = pool[i++];
        LSTORE         = pool[i++];
        FSTORE         = pool[i++];
        DSTORE         = pool[i++];
        ASTORE         = pool[i++];
        POP            = pool[i++];
        POP2           = pool[i++];
        DUP            = pool[i++];
        DUP_X1         = pool[i++];
        DUP_X2         = pool[i++];
        DUP2           = pool[i++];
        DUP2_X1        = pool[i++];
        DUP2_X2        = pool[i++];
        SWAP           = pool[i++];
        IADD           = pool[i++];
        LADD           = pool[i++];
        FADD           = pool[i++];
        DADD           = pool[i++];
        ISUB           = pool[i++];
        LSUB           = pool[i++];
        FSUB           = pool[i++];
        DSUB           = pool[i++];
        IMUL           = pool[i++];
        LMUL           = pool[i++];
        FMUL           = pool[i++];
        DMUL           = pool[i++];
        IDIV           = pool[i++];
        LDIV           = pool[i++];
        FDIV           = pool[i++];
        DDIV           = pool[i++];
        IREM           = pool[i++];
        LREM           = pool[i++];
        FREM           = pool[i++];
        DREM           = pool[i++];
        INEG           = pool[i++];
        LNEG           = pool[i++];
        FNEG           = pool[i++];
        DNEG           = pool[i++];
        ISHL           = pool[i++];
        LSHL           = pool[i++];
        ISHR           = pool[i++];
        LSHR           = pool[i++];
        IUSHR          = pool[i++];
        LUSHR          = pool[i++];
        IAND           = pool[i++];
        LAND           = pool[i++];
        IOR            = pool[i++];
        LOR            = pool[i++];
        IXOR           = pool[i++];
        LXOR           = pool[i++];
        I2L            = pool[i++];
        I2F            = pool[i++];
        I2D            = pool[i++];
        L2I            = pool[i++];
        L2F            = pool[i++];
        L2D            = pool[i++];
        F2I            = pool[i++];
        F2L            = pool[i++];
        F2D            = pool[i++];
        D2I            = pool[i++];
        D2L            = pool[i++];
        D2F            = pool[i++];
        I2B            = pool[i++];
        I2C            = pool[i++];
        I2S            = pool[i++];
        LCMP           = pool[i++];
        FCMPL          = pool[i++];
        FCMPG          = pool[i++];
        DCMPL          = pool[i++];
        DCMPG          = pool[i++];
        IFEQ           = pool[i++];
        IFNE           = pool[i++];
        IFLT           = pool[i++];
        IFGE           = pool[i++];
        IFGT           = pool[i++];
        IFLE           = pool[i++];
        IF_ICMPEQ      = pool[i++];
        IF_ICMPNE      = pool[i++];
        IF_ICMPLT      = pool[i++];
        IF_ICMPGE      = pool[i++];
        IF_ICMPGT      = pool[i++];
        IF_ICMPLE      = pool[i++];
        IF_ACMPEQ      = pool[i++];
        IF_ACMPNE      = pool[i++];
        GOTO           = pool[i++];
        IRETURN        = pool[i++];
        LRETURN        = pool[i++];
        FRETURN        = pool[i++];
        DRETURN        = pool[i++];
        ARETURN        = pool[i++];
        RETURN         = pool[i++];
        GETSTATIC      = pool[i++];
        PUTSTATIC      = pool[i++];
        GETFIELD       = pool[i++];
        PUTFIELD       = pool[i++];
        INVOKEVIRTUAL  = pool[i++];
        INVOKESPECIAL  = pool[i++];
        INVOKESTATIC   = pool[i++];
        INVOKEINTERFACE= pool[i++];
        NEW            = pool[i++];
        NEWARRAY       = pool[i++];
        ANEWARRAY      = pool[i++];
        ARRAYLENGTH    = pool[i++];
        ATHROW         = pool[i++];
        CHECKCAST      = pool[i++];
        INSTANCEOF     = pool[i++];
        IFNULL         = pool[i++];
        IFNONNULL      = pool[i++];
        TABLESWITCH    = pool[i++];
        LOOKUPSWITCH   = pool[i++];
        MULTIANEWARRAY = pool[i++];
        IALOAD         = pool[i++];
        LALOAD         = pool[i++];
        FALOAD         = pool[i++];
        DALOAD         = pool[i++];
        AALOAD         = pool[i++];
        BALOAD         = pool[i++];
        CALOAD         = pool[i++];
        SALOAD         = pool[i++];
        IASTORE        = pool[i++];
        LASTORE        = pool[i++];
        FASTORE        = pool[i++];
        DASTORE        = pool[i++];
        AASTORE        = pool[i++];
        BASTORE        = pool[i++];
        CASTORE        = pool[i++];
        SASTORE        = pool[i++];
        IINC           = pool[i++];
        MONITORENTER   = pool[i++];
        MONITOREXIT    = pool[i];
    }

    private VmOpcodes() {}
}
